"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[\uf054](white)"
vicmd_symbol = "[\ue62b](white)"
error_symbol = "[\uf054](white)"

[git_status]
disabled = true

[git_branch]
format = '\($branch\)'

[cmd_duration]
disabled = true
